# Generated by Django 3.0.7 on 2020-07-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='portafolio', max_length=100)),
                ('link', models.CharField(default='link_solucion', max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='none', upload_to='portafolio')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('title', models.CharField(default='servicio', max_length=200)),
                ('link', models.CharField(default='link_servicio', max_length=50)),
                ('text', models.TextField()),
                ('image', models.ImageField(default='none', upload_to='servicio')),
                ('number', models.BigAutoField(default='1', primary_key=True, serialize=False)),
            ],
        ),
    ]
