# Generated by Django 3.0.7 on 2020-07-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='number',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
        ),
    ]
