# Generated by Django 3.0.7 on 2020-06-22 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='Portafolio',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Servicio',
        ),
    ]
