# Generated by Django 3.0.7 on 2020-06-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200623_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='service',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='image',
            field=models.ImageField(upload_to='index'),
        ),
    ]
