# Generated by Django 3.0.7 on 2020-07-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200702_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='number',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
