# Generated by Django 3.0.7 on 2020-06-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200623_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='image',
            field=models.ImageField(upload_to='index/static/portafolio'),
        ),
    ]
