# Generated by Django 3.0.7 on 2020-06-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20200623_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='image',
            field=models.ImageField(default='none', upload_to='servicio'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='title',
            field=models.CharField(default='portafolio', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='title',
            field=models.CharField(default='servicio', max_length=200),
        ),
    ]
