# Generated by Django 3.0.7 on 2020-06-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20200629_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='link',
            field=models.CharField(default='link_servicio', max_length=50),
        ),
    ]
